name: Build and Test crAPI
on:
  push:

jobs:
  build-and-test-images:
    runs-on: ubuntu-20.04
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build images
        run: ./deploy/docker/build-all.sh
        env:
          DOCKER_REPO: location
          VERSION: testing
      - name: Launch crAPI
        run: docker compose up -d
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Stage data for testing
        run: |
          npm install
          node .
        working-directory: baseline-script
        env:
          USERS_TO_BASELINE: 1
